### ISSUE TITLE
Add our own tokens

### ISSUE THREAD

**Issue by RodionMun** [ZilStream/frontend#3]
Hello! I see that this site grabs token list from the: https://api.zilstream.com/tokens

Is there any way we could add some custom tokens to it? :)

Or where I can found back-end source code as well do build our own (just for personal usage from localhost).

I want to monitor some user-created tokens just for research purpose

**Comment by melvinbeemer** [comment]
Hey, that's a good idea. I think I may have something like this in the works as part of an upcoming feature. Could create an API endpoint there where you could enter any contract address

**Comment by ziltings** [comment]
I second this. The form route of adding a token can be replaced with a PR. The discussion can be public as well.

**Comment by melvinbeemer** [comment]
There is now a repo for this [here](https://github.com/ZilStream/tokens).
